[[section-architecture-constraints]]
== Requisitos de arquitectura


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

=== 2.1 Restricciones técnicas
[options="header",cols="1,2"]
|===
|Restricción|Explicación
| docker |  contenedores docker empleados para el despliegue de la aplicación.
| solid app |  tecnología fundamental para poder garantizar la confidencialidad 
				de los datos manejados de forma que se conforma una red de persistencia
				descentralizada.
| typescript |  lenguaje de programacion empleado para la implementación de
				la lógica de negocio del sistema.
| react |  es la libreria que sera utilizada para la construcción del front-end
				del sistema.
|===

=== 2.2 Organizacion
[options="header",cols="1,2"]
|===
|Restricción|Explicación
| tiempo / planificación |  el sistema debe de cumplir con los requisitos funcionales
				planteados antes de la ultima entrega de la asginatura. Asi como cumplir con
				las entregas parciales solicitadas.
| control de versiones git |  como decision impuesta se debe utilizar control de
				versiones con git para gestionar el desarrollo del proyecto.
| equipo fijo |  el equipo es impuesto por la organizacion de la asignatura, tanto
				su tamaño como sus integrantes.
|===

=== 2.3 políticas
[options="header",cols="1,2"]
|===
|Restricción|Explicación
| ley orgánica de protección de datos |  a nivel de cumplimiento de la
				legislación española debemos tener especial cuidado en el trato de
				los datos sensibles de los usuarios de nuestra aplicación.
| idioma | se empleará el idioma castellano tanto en la documentación como
				en la implementación de la aplicación aunque se podrá internacionalizar
				en un futuro.
| arc42 |  como decisión impuesta debemos seguir esta plantilla para la realización
				de esta documentación.
|===
