[[section-concepts]]
== Conceptos transversales
[role="arc42help"]

=== Modelo de dominio
****

El usuario tendrá una lista de licores donde este podrá seleccionar los que desee, meterlos en un carrito y posteriormente acceder a la compra.

Una vez se acceda a la compra, el sistema calculará automaticamente los costes de envío utilizando la dirección del usuario, que se encontrará en su POD, y los costes de envío en relacion de la distancia del centro de distribución a la dirección del cliente.

El sistema mostrará el precio final y cuando el usuario acepte se registrará la venta y su envío.

Además la aplicación permitirá que los usuarios vean los pedidos realizados que tienen.

****

=== Experiencia de usuario
****

La aplicación sigue una interfaz simple y minimalista con la idea de que sea fácil e intuitiva de usar para los usuarios.

****

=== Internacionalización
****

La aplicación principalmente esta realizada en español aunque en un futuro se podría ampliar a más idiomas.

****

=== Seguridad y Privacidad
****

La seguridad y la privacidad es un objetivo muy importante de la aplicación. Se trata de tener una aplicación descentralizada gracias al uso de los PODs donde se almacenan los datos de los usuarios de forma privada y estos son los propietarios de sus propios datos y ellos mismos deciden a quién dar acceso.

Además de en los PODs también vamos a tener datos guardados en una base de datos MongoDB.

****

=== Pruebas
****

A medida de que la aplicación esté en funcionamiento y según se vaya actualizando vamos a realizar pruebas exhaustivas para asegurarnos de que todo esta funcionando correctamente.

****