[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****

**Decisiones Tomadas**

* El idioma de la documentación será el castellano, pues es el lenguaje nativo de los miembros del equipo y nos
resultará más claro y comprensible en este idioma.

* Uso de la bilbioteca Boostrap para la elaboración de las hojas de estilo de tal forma que nuestra aplicación resulte 
más atractiva visualmente para los usuarios.

* Dado que nuestro proyecto será creado junto al proyecto Solid, algunos de nuestros datose serán almacenados en los 
Solid Pods. Junto a esto, la base de datos que utilizaremos será relacional debido a la familizarización de los miembros del equipo con este modelo. Aún está
por decidir la base de datos concreta a utilizar.