[[section-glossary]]
== Glossary



[role="arc42help"]
****
.Contents
The most important domain and technical terms that your stakeholders use when discussing the system.

You can also see the glossary as source for translations if you work in multi-language teams.

.Motivation
You should clearly define your terms, so that all stakeholders

* have an identical understanding of these terms
* do not use synonyms and homonyms

.Form
A table with columns <Term> and <Definition>.

Potentially more columns in case you need translations.

****

|===
| Término         | Definición
| Solid    | Proyecto de descentralización de datos en la web que permiten al 
usuario final decidir dónde se van a almacenar sus datos mejorando así la 
privacidad.
| TypeScript    | Lenguaje de programación libre y de código abierto desarrollado y mantenido por Microsoft. Es un superconjunto de JavaScript, que esencialmente añade tipos estáticos y objetos basados en clases.
| React    | Biblioteca Javascript de código abierto diseñada para crear interfaces de usuario con el objetivo de facilitar el desarrollo de aplicaciones en una sola página.
| Stakeholder    | Entidad que afecta, es afectado o puede contribuir al sistema y su arquitectura, entendiendose entidad como persona, organizacion, empresa, etc.
| POD    | Los pods, personal online data stores, son como servidores web personales seguros para tus datos.

Puedes almacenar cualquier tipo de información en un Pod de Solid, utilizando formatos y protocolos de datos estándar, abiertos e interoperables. Además, controlas el acceso a los datos de tu Pod y decides con quién quieres compartir qué datos. Puedes revocar el acceso en cualquier momento.
|===
